#
# Checks that the PDF version of the Programming Cryptol book was updated
# if any of its consitituent files were changed.
#

name: Programming Cryptol PDF Update
on: [pull_request]


jobs:
    update_needed:
        runs-on: ubuntu-latest
        steps:
          - id: checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - name: "Check if update to local PDF is needed"
            run: |
                changed_files=$(git diff --name-only --diff-filter ACDMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
                # This will fail if any files have spaces in the names.
                bash .github/check_book_update.sh $changed_files

